### ISSUE TITLE
Creating .kin0 files

### ISSUE THREAD

**Issue by isabelrem** [seanjosephjurgens/UKBB_200KWES_CVD#1]
Hello,

I am trying to implement your GENESIS code as part of my MSc Bioinformatics thesis. However, I am having real issues generating the .kin0 file as the HPC I am using does not have enough RAM. I wondered if you came across this issue, and how you overcame it? Do you still have your .kin0 file, and what was it build from? I believe I may be working with the same release of UKBB Exomes as in your paper.

Thank you so much,

Isabel

**Comment by seanjosephjurgens** [comment]
Thanks for your question. This issue has been resolved outside of the GitHub space.

Summary of problem and solution:
Issue --> working memory issue when running KING to compute pairwise relationship estimates using standard parameters.
Reason --> the entire WES dataset was presented to KING (without pre-filtering of relevant variants).
Solution --> apply filters to the variants used for relationship computation (for example, MAF>0.1%, hwe-p <0.00001, pruning). NB: these filters may (and likely should) differ strongly from the variants you'd want to include in the association testing phase.

Issue will now be closed.
